export const ADD_PERSON_TO_FAVORITES = "ADD_PERSON_TO_FAVORITES";
export const REMOVE_PERSON_FROM_FAVORITES = "REMOVE_PERSON_FROM_FAVORITES";
export const REMOVE_ALL_PERSONS_FROM_FAVORITES = "REMOVE_ALL_PERSONS_FROM_FAVORITES";